eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true
        hostname: localhost
        non-secure-port-enabled: true
        instance-id: ${spring.application.name}:${server.port}

spring:
  application:
    name: MicroserviceConcours
  

  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
    password: aaaa

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
    

server:
  port: 8092

logging:
  level:
    org.springframework.mail: DEBUG
    org.springframework.web: DEBUG


file:
  upload-dir: uploads





