spring:
  application:
    name: gstionConcours

  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
    password: qqqq

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    

server:
  port: 8091

logging:
  level:
    org.springframework.mail: DEBUG
    org.springframework.web: DEBUG

