spring:
  application:
    name: gstionConcours

  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
    password: qqqq

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
    

server:
  port: 8092

logging:
  level:
    org.springframework.mail: DEBUG
    org.springframework.web: DEBUG


file:
  upload-dir: uploads





